version: "3.8"

services:
  ofelia:
    name: duckdns-ofelia
    image: mcuadros/ofelia:latest
    depends_on:
      - bot
    restart: unless-stopped
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  bot:
    name: duckdns-bot
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./config
        target: /duckdns-bot/config
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 10m"
      ofelia.job-exec.datecron.command: "curl http://health.hh.home/ping/9cbf734d-20e8-4178-b59a-b7411747839f && python /duckdns-bot/dockdns_bot.py && curl http://health.hh.home/ping/9cbf734d-20e8-4178-b59a-b7411747839f"
