services:
  ofelia:
    container_name: duckdns-bot-ofelia
    image: mcuadros/ofelia:latest
    depends_on:
      - bot
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  bot:
    build: .
    container_name: duckdns-bot-script
    command: ['tail', '-f', '/dev/null']
    volumes:
      - type: bind
        source: ./config
        target: /duckdns-bot/config
      - type: bind
        source: ./logs
        target: /duckdns-bot/logs
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "0 */11 * * * *"
      ofelia.job-exec.datecron.command: "/bin/sh /duckdns-bot/scripts/run.sh"